### PR TITLE
use ngbDropdown for color selection in both top menu and layers menu

### PR DESCRIPTION
**Pull request by ed2k**
#43 #42 #33

### CODE REVIEW

**Comment by ed2k** [comment]
not sure how to detect when there isn't enough space.
the control point color only showing when the polygon is not closed.

**Comment by erikbernheim** [comment]
I would look at the height of the toolbar, and if it's higher than the normal value, display the drop-down, otherwise display the normal buttons. 

like that way of handling the control points. That sounds good.

**Comment by ed2k** [comment]
Screenshot from 2020-06-02 20-54-10
Screenshot from 2020-06-02 20-55-01
Screenshot from 2020-06-02 20-56-35

**Comment by erikbernheim** [comment]
Looks really good. I won't have any time for review until Friday or Saturday, but I will merge and deploy as soon as I can.

**Comment by erikbernheim** [comment]
I had to revert this PR. This issue needs to be resolved before it can be merged. 
image

**Comment by erikbernheim** [comment]
Even if I scroll down, the bottom button does not appear. Scrolling is also
not a good solution, the drop-down needs to appear above the parent.

**Comment by ed2k** [comment]
trid to change the z-index, seems no effect. how about as a temporary solution `placement="right"`

**Comment by erikbernheim** [comment]
Can you post a screenshot? Otherwise maybe we could just change it from and drop-down within a dropdown to maybe a modal popup?

**Comment by ed2k** [comment]
Screenshot from 2020-06-07 10-58-47

**Comment by erikbernheim** [comment]
I don't like seeing the drop-down scroll when there are only a few layers. How about converting it to a modal. You can make it a button, that calls a function onclick to open a modal to change the color.

**Comment by ed2k** [comment]
Screenshot from 2020-06-07 11-31-44
modal seems requiring more mouse move, best case is to have selection surround the click button. now I place them top-left, to get away with scroll appearing.

**Comment by erikbernheim** [comment]
That works perfect. Create a new PR because this one has been closed, and I
will merge.

**Pull request merged**
